/**
 * Merge finished clip files into ONE "full edit" video (user opt-in).
 *
 * Strategy: ffmpeg concat demuxer. All inputs come from the same encode pass
 * (identical codec/size/fps), so pass 1 is a lossless, near-instant stream
 * copy. If a container/timestamp quirk rejects the copy, pass 2 re-encodes
 * with the same profile the clips used. Never throws — a merge failure must
 * never cost the user their finished clips.
 */
import { execFile } from "child_process";
import { promisify } from "util";
import fs from "fs";

const execFileAsync = promisify(execFile);

/** Indices of `startsSec` sorted chronologically (stable on ties) — the merged
 *  edit should replay the source video's story in order, regardless of the
 *  order the scorer picked the moments in. */
export function chronologicalOrder(startsSec: number[]): number[] {
  return startsSec
    .map((start, index) => ({ start, index }))
    .sort((a, b) => a.start - b.start || a.index - b.index)
    .map((e) => e.index);
}

/** Concat-demuxer list file content. Single quotes inside a path use the
 *  close-escape-reopen idiom ('\''). Paths are generated by us (clip_NNN.mp4
 *  inside a mkdtemp dir), so newlines can't occur — but strip them anyway so
 *  a weird tmpdir can never inject extra directives. */
export function buildConcatList(paths: string[]): string {
  return (
    paths
      .map((p) => `file '${p.replace(/[\r\n]/g, "").replace(/'/g, `'\\''`)}'`)
      .join("\n") + "\n"
  );
}

export type ConcatExec = (
  file: string,
  args: string[],
  opts: { maxBuffer: number; timeout: number },
) => Promise<unknown>;

export async function concatClipFiles(opts: {
  /** Absolute clip paths, already in the desired play order (2+ required). */
  inputs: string[];
  /** Output .mp4 path — the list file is written next to it as `<output>.txt`. */
  output: string;
  ffmpegPath: string;
  /** Re-encode fallback mirrors the clip encode profile. */
  encode: { preset: string; crf: string };
  copyTimeoutMs?: number;
  reencodeTimeoutMs?: number;
  /** Injectable for tests. */
  execImpl?: ConcatExec;
  warn?: (msg: string) => void;
}): Promise<boolean> {
  const { inputs, output, ffmpegPath, encode } = opts;
  if (inputs.length < 2) return false;
  const exec: ConcatExec = opts.execImpl ?? ((f, a, o) => execFileAsync(f, a, o));
  const listPath = `${output}.txt`; // same scratch dir — dies with the job
  try {
    fs.writeFileSync(listPath, buildConcatList(inputs));
  } catch (err) {
    opts.warn?.(`[combine] could not write concat list: ${String(err)}`);
    return false;
  }
  const baseArgs = ["-y", "-f", "concat", "-safe", "0", "-i", listPath];
  try {
    await exec(ffmpegPath, [...baseArgs, "-c", "copy", "-movflags", "+faststart", output], {
      maxBuffer: 20 * 1024 * 1024,
      timeout: opts.copyTimeoutMs ?? 120_000,
    });
    return true;
  } catch (err) {
    opts.warn?.(`[combine] stream-copy concat failed — retrying with re-encode: ${String(err)}`);
  }
  try {
    await exec(
      ffmpegPath,
      [
        ...baseArgs,
        "-c:v", "libx264", "-preset", encode.preset, "-crf", encode.crf,
        "-profile:v", "high", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "128k",
        "-movflags", "+faststart",
        output,
      ],
      { maxBuffer: 20 * 1024 * 1024, timeout: opts.reencodeTimeoutMs ?? 600_000 },
    );
    return true;
  } catch (err) {
    opts.warn?.(`[combine] re-encode concat failed: ${String(err)}`);
    return false;
  }
}
